### ISSUE TITLE
Overwriting application to use DS.FixtureAdapter in start-app.js

### ISSUE THREAD

**Issue by corydobson** [switchfly/ember-mocha#21]
### Hi Ember Mocha Team! 

I'm having real problems trying to switch out the adapters for my test application. I'm using Ember CLI and Ember CLI Mocha. 

It is better described on my Ember-CLI issue here -> https://github.com/ember-cli/ember-cli/issues/3249 

I've also tried 
```
  var attributes = Ember.merge({ApplicationAdapter:DS.FixtureAdapter.extend({})}, config.APP);

```
with no luck. :( Is there something I'm missing here? Or is this part of a larger issue?

**Comment by corydobson** [comment]
cc/ @dgeb

**Comment by dgeb** [comment]
@corydobson hey Cory - check out [my response](https://github.com/ember-cli/ember-cli/issues/3249#issuecomment-74130938) to your ember-cli issue and let me know if you run into problems with either approach.
