### ISSUE TITLE
Ember testing helpers not found

### ISSUE THREAD

**Issue by kiwiupover** [switchfly/ember-mocha#25]
I'm not able to uses the ember helpers `andThen` or `click` when I use ember-mocha and ember-cli-mocha. This this a bug or a feature?

**Comment by rwjblue** [comment]
The `andThen`, `click`, etc helpers are only available in acceptance tests (which are not provided by ember-mocha and ember-cli-mocha).

**Comment by kiwiupover** [comment]
Thanks Robert @rwjblue

**Comment by kiwiupover** [comment]
@rwjblue I was reading this doc 
http://emberjs.com/guides/testing/testing-components/#toc_interacting-with-components-in-the-dom

And it is out dated in that is shows the testing helpers `andThen` and `click` should I update the doc?

**Comment by rwjblue** [comment]
Yes, please.  It will need to be updated in both `emberjs/website` and `emberjs/guides` (we are in a transition period).
