### ISSUE TITLE
Add integration test module

### ISSUE THREAD

**Issue by dgeb** [switchfly/ember-mocha#26]
Expose the integration test module from https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-integration.js

**Comment by drapergeek** [comment]
I've started using `ember-mocha` on a new project this week and my acceptance/integration tests don't seem to respect `andThen` in mocha, I've been forced to use the `done()` option which is not expected. Is this missing module that answer to that issue?

**Comment by dgeb** [comment]
@drapergeek I've been successfully using `andThen` in my acceptance tests. I will publish an example repo soon.

Closing this issue now that the vanilla integration test module has gone away, so it no longer needs to be exposed.

**Comment by jamesdixon** [comment]
@dgeb when using `andThen` in your acceptance tests, do you still need to call `done()`? I'm seeing some strange behavior where in the console-based Testem runner, I see that there was a timeout in my test, yet on the web-based Testem runner, it's passing. Any ideas?

**Comment by jamesdixon** [comment]
As a follow-up, I'm only seeing the timeouts in the PhantomJS runner and not in Chrome.

**Comment by signal-intrusion** [comment]
Me too. Timeouts in PhantomJS usually only on the first acceptance test, even when calling `done()`.
