### ISSUE TITLE
acceptance testing window like qunit

### ISSUE THREAD

**Issue by danielspaniel** [switchfly/ember-mocha#33]
Well.. The issue is when I switched from Qunit to Mocha, the acceptance tests where I "visit('/soandso')"  no longer put the output into a window on the side as Qunit did. 

 Before mocha installation there was this in the test_helper.js file:

```js
document.write('<div id="ember-testing-container"><div id="ember-testing"></div></div>');

QUnit.config.urlConfig.push({ id: 'nocontainer', label: 'Hide container'});
var containerVisibility = QUnit.urlParams.nocontainer ? 'hidden' : 'visible';
document.getElementById('ember-testing-container').style.visibility = containerVisibility;
```

Could that have made the difference?  
What do I have to do to put mocha acceptance testing html into it's own 'irfame' ??

**Comment by danielspaniel** [comment]
I found this url: https://github.com/WMeldon/ember-cli-
todos/blob/125f28a734b5f600b83420d64b92bab1ea17c8ed/tests/index.html
 
and added the css for the #ember-testing-container .. and that did it. 

 I notice there there is no css for ember-mocha project. Maybe this kind of css should go in there? 
 Not sure if I am missing something though.

**Comment by dgeb** [comment]
Please try with the latest ember-mocha and ember-cli-mocha (both v0.7.0) and call `ember g ember-cli-mocha`. Let me know if you continue to have any styling problems.

**Comment by mupkoo** [comment]
I have the following things in my test helper file

```
if (window.location.search.indexOf('nocontainer') > -1) {
    Ember.$('#ember-testing-container').css({
        visibility: 'hidden'
    });
}

Ember.$('body').on('click.mocha-stats', '#mocha-stats a', function (e) {
    e.preventDefault();
    return false;
});
```

Having this allows me to navigate to `?nocontainer` to hide the container and use the mocha buttons to filter only the failing tests.
