### ISSUE TITLE
Minor version bump, please.

### ISSUE THREAD

**Issue by bjornstar** [switchfly/ember-mocha#36]
When you update dependencies with major version bumps, the least you can do is bump your minor version. That way you're not breaking the builds of people who only allow patch level changes.

chai 1.10 to 2.3.0 is a major version bump
mocha 2.1.0 to 2.2.4 is a minor version bump
ember-test-helpers 0.4.3 to 0.4.4 had [a painful oversight] (https://github.com/switchfly/ember-test-helpers/issues/47)

**Comment by dgeb** [comment]
Sorry about this.

I've deleted v0.6.3 of ember-mocha from [ember-mocha-builds](https://github.com/switchfly/ember-mocha-builds).

I've pushed v0.7.0 of both ember-mocha and ember-cli-mocha.
