### ISSUE TITLE
Setting test reporter

### ISSUE THREAD

**Issue by natecox** [switchfly/ember-mocha#37]
This may be a dumb question, but how would I go about changing the test reporter for ember-mocha? I'm not a big fan of the basic reporter being used by `ember test` but can't seem to find documentation on how to go about changing it.

**Comment by nurazem** [comment]
:+1: I'm looking for the exact same thing. http://mochajs.org/#reporters states that only this reporter is supported by Mocha. This reporter doesn't work well for me because I can't scroll on the tests page and 'hide passed tests' option has no effect on the output.

**Comment by natecox** [comment]
@nurazem I did some research on this and found that ember is actually using the testem package to run its tests, which comes with a limited number of reporters.

My `testem.json` file currently looks like this:

```
{
  "framework": "mocha",
  "test_page": "tests/index.html?hidepassed",
  "reporter": "tap",
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}
```

The options for reporter are:
* tap
* xunit
* dot
* teamcity

I'm using `tap`, which is the default option and seems to be the best of the available options. `dot` may be of interest to you because it has way less scrolling.

The takeaway from this is that I would really like to be able to just use mocha's reporters.

**Comment by mmahalwy** [comment]
@natecox I cannot get the 'dot' reporter to even work :(

**Comment by mmahalwy** [comment]
So i discovered you can indeed change the reporter by 
```
mocha.reporter('html');
```

In your test-helper.js. But its still a pain as there is no good html reporters...
