### ISSUE TITLE
[Question] Does a test module provide access to the container?

### ISSUE THREAD

**Issue by pixelhandler** [switchfly/ember-mocha#50]
I'd like to use `this.container` in tests (ember-qunit) does this. I'm not sure if ember-mocha does the same. 

Using Ember Mocha how can I access the container in an unit test?

This is the Unit test I have as a blueprint for an addon: https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/blueprints/model-test/files/tests/unit/__path__/__test__.js however a consuming app may not use QUnit but ember-mocha instead. So I'd like to provide an example for testing with ember-mocha (addon and app not using ember-data).

cc/ @oliverbarnes

**Comment by rwjblue** [comment]
All of the context props from ember-test-helpers are setup [here](https://github.com/switchfly/ember-mocha/blob/master/lib/ember-mocha/mocha-module.js#L26-L33). That should include `this.container` and `this.registry` (though both of those are technically private).

**Comment by rwjblue** [comment]
Can you provide an example scenario, where `this.container` is not setup properly?

**Comment by pixelhandler** [comment]
@oliverbarnes can you link to your test here?

**Comment by oliverbarnes** [comment]
sure, here it is - it's the same one I posted on slack: https://github.com/oliverbarnes/participate/blob/supporting-a-proposal/tests/unit/models/proposal-test.js

**Comment by oliverbarnes** [comment]
Right now I'm hitting an error previous to the missing container one, though: 
```
TestLoader Failures
client/tests/unit/models/proposal-test: could not be loaded ‣
TypeError: ember_mocha.describe is not a function
    at http://localhost:7357/assets/client.js:2616:15
    at mod.state (http://localhost:7357/assets/vendor.js:150:29)
    at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:40:24)
    at http://localhost:7357/assets/test-support.js:14840:16
```

**Comment by rwjblue** [comment]
ember-mocha does not export `describe`.  `describe` is the default `mocha` describe, and if you want the vanilla version you can import it as `import { describe } from 'mocha';`, but it looks like you actually want `describeModule` which is exported by ember-mocha (and should have `this.container` set properly on the context).

**Comment by oliverbarnes** [comment]
thanks @rwjblue that's good to know. I'm now trying

```
describeModule('model:proposal', 'Unit | Model| Proposal',{}, function() {

  // describe('#toggleSupport', function() {
    before(function() {
      subject = Proposal.create();
    });

    // describe('when proposal is not supported yet', function() {
      it('adds a support to it', function() {
        // expect(this.subject().get('supports')).to.eql([]);
        expect(subject.toggleSupport()).to.be.true;
      });
    // });
  // });
});
```

And the test seems to load. I'm avoiding using the container and creating the resource directly, I'll keep you both posted

**Comment by oliverbarnes** [comment]
Actually there's a loading problem again, but with `before` and `beforeEach`:

```
TestLoader Failures
client/tests/unit/models/proposal-test: could not be loaded ‣
TypeError: ember_mocha.beforeEach is not a function
```

Though I'm importing both:

```
import {
  describeModule,
  before,
  beforeEach,
  it
} from 'ember-mocha';
```

@pixelhandler is cloning my repo and taking this for a drive, let's se what comes up. I'm probably doing something not that bright somewhere ;)

**Comment by pixelhandler** [comment]
@oliverbarnes so `this.container` does work with `describeModule` see https://github.com/oliverbarnes/participate/pull/101  but I was not able to figure out how to use before/after or beforeEach/afterEach with `describeModule`.
