### ISSUE TITLE
ember-test-helpers 0.5.9

### ISSUE THREAD

**Issue by mattgrannary** [switchfly/ember-mocha#56]
Has a new build been released that includes the fallbackRegistry feature? Really need this functionality for a component integration test. 

switchfly/ember-test-helpers#96

**Comment by rwjblue** [comment]
I don't believe that a tagged build has been done yet, but I just merged https://github.com/switchfly/ember-mocha/pull/55 so you should be able to grab a canary build.

**Comment by mattgrannary** [comment]
:+1: Awesome. This fixes a major roadblock I was having setting up proper integration tests for my components.

**Comment by dgeb** [comment]
v0.8.2 has just been released. Thanks for the nudge. :shipit:
