### ISSUE TITLE
afterEach block in describeComponent

### ISSUE THREAD

**Issue by spinlock99** [switchfly/ember-mocha#67]
I'm having trouble running an `afterEach` block inside a `describeComponent` block:

    /* jshint expr:true */
    import { expect } from 'chai';
    import {
      describeComponent,
      afterEach,
      it
    } from 'ember-mocha';
    import sinon from 'sinon';

    describeComponent(
      'table-header',
      'TableHeaderComponent',
      {
        // Specify the other units that are required for this test
        // needs: ['component:foo', 'helper:bar'],
        unit: true
      },
      function () {
        var sandbox = sinon.sandbox.create();

        afterEach(function () {
          sandbox.restore();
        });
        ...

Fails with:

    TypeError: (0 , _emberMocha.afterEach) is not a function
    at http://localhost:7357/assets/tests.js:520:31
    at Suite.moduleBody (http://localhost:7357/assets/test-support.js:2055:7)
    at Object.context.describe.context.context (http://localhost:7357/assets/test-support.js:15276:12)
    at Object.createModule (http://localhost:7357/assets/test-support.js:2060:13)
    at describeComponent (http://localhost:7357/assets/test-support.js:1930:18)
    at http://localhost:7357/assets/tests.js:513:37
    at mod.state (http://localhost:7357/assets/vendor.js:157:29)
    at tryFinally (http://localhost:7357/assets/vendor.js:37:14)
    at requireModule (http://localhost:7357/assets/vendor.js:155:5)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)

but, the test works fine if I comment out the `afterEach` block.

Is `afterEach` not supported in `describeComponent` blocks or am I doing something wrong here?

Thanks

**Comment by rwjblue** [comment]
`afterEach` isn't exported from `ember-mocha` module ([see here](https://github.com/switchfly/ember-mocha/blob/master/lib/ember-mocha.js#L7-L13)), it is exported from `mocha` module ([see here](https://github.com/switchfly/ember-mocha/blob/master/lib/mocha.js#L70-L79)).

_tldr;_ change to use `import { afterEach } from 'mocha'`

**Comment by rwjblue** [comment]
We have been discussing (in ember-qunit) to export all the things from the main module, the current exports are non-obvious and folks generally get tripped up (like you have reported here) initially.

**Comment by rwjblue** [comment]
I'm fairly sure the above will fix the issue for you, so I'm going to go ahead and close for now...

**Comment by spinlock99** [comment]
That was exactly the issue. Thanks so much for your help.
